const faker = require('faker');
const fs = require('fs');

for(let i = 0; i<500; i++){

const s1_t1_pk = faker.getNumber();
fs.appendFileSync(`insert into s1.t1(c1, c2) values (${s1_t1_pk}, <%t1~_~c2~_~s2_t2_pk~_~c1~_~s1_t1_pk%>);`);
const s1_t1_pk = faker.getNumber();
fs.appendFileSync(`insert into s1.t1(c1, c2) values (${s1_t1_pk}, <%t1~_~c2~_~s2_t2_pk~_~c1~_~s1_t1_pk%>);`);
const s2_t2_pk = faker.getNumber();
fs.appendFileSync(`insert into s2.t2(c1, c2) values (${s2_t2_pk}, <%t2~_~c2~_~s2_t2_pk~_~c1~_~s2_t2_pk%>);`);
const s1_t1_pk = faker.getNumber();
fs.appendFileSync(`insert into s1.t1(c1, c2) values (${s1_t1_pk}, <%t1~_~c2~_~s2_t2_pk~_~c1~_~s1_t1_pk%>);`);
const s2_t2_pk = faker.getNumber();
fs.appendFileSync(`insert into s2.t2(c1, c2) values (${s2_t2_pk}, <%t2~_~c2~_~s2_t2_pk~_~c1~_~s2_t2_pk%>);`);
const s1_t1_pk = faker.getNumber();
fs.appendFileSync(`insert into s1.t1(c1, c2) values (${s1_t1_pk}, <%t1~_~c2~_~s2_t2_pk~_~c1~_~s1_t1_pk%>);`);
const s1_t1_pk = faker.getNumber();
fs.appendFileSync(`insert into s1.t1(c1, c2) values (${s1_t1_pk}, <%t1~_~c2~_~s2_t2_pk~_~c1~_~s1_t1_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_messages_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.messages(c1, c2) values (${myapp_test_messages_pk}, <%messages~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_messages_pk%>);`);
const myapp_test_tags_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.tags(c1, c2) values (${myapp_test_tags_pk}, <%tags~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_tags_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_tags_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.tags(c1, c2) values (${myapp_test_tags_pk}, <%tags~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_tags_pk%>);`);
const myapp_test_messages_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.messages(c1, c2) values (${myapp_test_messages_pk}, <%messages~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_messages_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_tags_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.tags(c1, c2) values (${myapp_test_tags_pk}, <%tags~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_tags_pk%>);`);
const myapp_test_messages_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.messages(c1, c2) values (${myapp_test_messages_pk}, <%messages~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_messages_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_messages_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.messages(c1, c2) values (${myapp_test_messages_pk}, <%messages~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_messages_pk%>);`);
const myapp_test_tags_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.tags(c1, c2) values (${myapp_test_tags_pk}, <%tags~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_tags_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_messages_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.messages(c1, c2) values (${myapp_test_messages_pk}, <%messages~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_messages_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_tags_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.tags(c1, c2) values (${myapp_test_tags_pk}, <%tags~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_tags_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_messages_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.messages(c1, c2) values (${myapp_test_messages_pk}, <%messages~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_messages_pk%>);`);
const myapp_test_tags_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.tags(c1, c2) values (${myapp_test_tags_pk}, <%tags~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_tags_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_messages_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.messages(c1, c2) values (${myapp_test_messages_pk}, <%messages~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_messages_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_tags_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.tags(c1, c2) values (${myapp_test_tags_pk}, <%tags~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_tags_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_messages_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.messages(c1, c2) values (${myapp_test_messages_pk}, <%messages~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_messages_pk%>);`);
const myapp_test_tags_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.tags(c1, c2) values (${myapp_test_tags_pk}, <%tags~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_tags_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
const myapp_test_users_pk = faker.getNumber();
fs.appendFileSync(`insert into myapp_test.users(c1, c2) values (${myapp_test_users_pk}, <%users~_~c2~_~s2_t2_pk~_~c1~_~myapp_test_users_pk%>);`);
